// GuidResolver.cs — Unity Editor tool to recover missing MonoBehaviour script
// references in prefabs/scenes/SOs by matching their serialized field shape
// against every MonoBehaviour and ScriptableObject in the project.
//
// Place under: Assets/Editor/GuidResolver.cs
// Open via:    "ER2 TOOLS > GUID Resolver"
//
// Workflow:
//   1) Make sure your source scripts (Assembly-CSharp + the ER2 SDK) are in the
//      project, and that AssetRipper's stub scripts have been REMOVED.
//   2) Click "Scan Project". The tool finds every MonoBehaviour reference whose
//      script GUID is missing, gathers the property names that appear in YAML
//      for each, and ranks every project script by how many of those property
//      names match its public/[SerializeField] fields.
//   3) Confident matches can be applied automatically. Ambiguous, partial or
//      no-match cases ask you to pick (or override) the right script via a
//      MonoScript field with built-in search.
//   4) "Apply" rewrites GUID references across Assets/ and ProjectSettings/.
//
// The tool does NOT touch source scripts or .meta of the target scripts.
// Always commit / back up before applying.

using UnityEngine;
using UnityEditor;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

public class GuidResolverWindow : EditorWindow
{
    private const string MenuPath = "ER2 TOOLS/Tools/GUIDs/GUID Resolver";

    // YAML system fields (auto-generated by Unity, not user-defined).
    private static readonly HashSet<string> SystemFields = new HashSet<string>(StringComparer.Ordinal)
    {
        "m_ObjectHideFlags", "m_CorrespondingSourceObject", "m_PrefabInstance",
        "m_PrefabAsset", "m_GameObject", "m_Enabled", "m_EditorHideFlags",
        "m_Script", "m_Name", "m_EditorClassIdentifier"
    };

    // Files we read during scanning (where MonoBehaviour blocks live).
    private static readonly HashSet<string> ScanExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        ".prefab", ".unity", ".asset"
    };

    // Files we patch when applying remap (broader: GUID refs appear in many text-serialized assets).
    private static readonly HashSet<string> PatchExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        ".unity", ".prefab", ".asset", ".mat", ".anim", ".controller", ".overridecontroller",
        ".mask", ".physicmaterial", ".physicsmaterial", ".physicsmaterial2d", ".mixer",
        ".spriteatlas", ".spriteatlasv2", ".playable", ".terrainlayer", ".lighting",
        ".giparams", ".rendertexture", ".cubemap", ".fontsettings", ".guiskin", ".flare",
        ".brush", ".shadervariants", ".preset", ".signal", ".meta"
    };

    private static readonly Regex ScriptGuidRegex = new Regex(
        @"m_Script:\s*\{[^}]*guid:\s*([0-9a-f]{32})", RegexOptions.Compiled);

    // Top-level field of a MonoBehaviour block: exactly two leading spaces, then identifier, then ':'.
    private static readonly Regex TopLevelFieldRegex = new Regex(
        @"^  ([a-zA-Z_][a-zA-Z0-9_]*):", RegexOptions.Compiled | RegexOptions.Multiline);

    private const float HighConfidenceCoverage = 1.0f;
    private const float PartialThreshold = 0.6f;
    private const float SecondBestThreshold = 0.8f; // for Likely vs Confident

    // ---------- Data ----------

    private class ScriptInfo
    {
        public string Guid;
        public Type Type;
        public string AssetPath;
        public string TypeName;
        public HashSet<string> Fields;
    }

    private class CandidateMatch
    {
        public ScriptInfo Script;
        public int Matched;
        public int YamlFieldsTotal;
        public int ScriptFieldsTotal;
        public float Coverage;          // matched / yamlTotal
        public List<string> UnknownInScript; // YAML fields not present in script
    }

    private enum Status { Confident, Likely, Ambiguous, Partial, NoMatch }

    private class MissingScriptEntry
    {
        public string MissingGuid;
        public HashSet<string> ObservedFields = new HashSet<string>();
        public List<string> UsedInFiles = new List<string>();
        public List<CandidateMatch> Candidates = new List<CandidateMatch>();
        public ScriptInfo SelectedOverride;
        public Status Status;
        public bool Apply = true;
        public bool Expanded;
    }

    // ---------- State ----------

    private List<MissingScriptEntry> _entries = new List<MissingScriptEntry>();
    private List<ScriptInfo> _allScripts = new List<ScriptInfo>();
    private Dictionary<string, ScriptInfo> _scriptByGuid = new Dictionary<string, ScriptInfo>();
    private Vector2 _scroll;
    private bool _scanned;
    private string _filter = "";

    // Cached styles
    private GUIStyle[] _statusStyles;

    [MenuItem(MenuPath)]
    private static void Open()
    {
        var w = GetWindow<GuidResolverWindow>(false, "GUID Resolver", true);
        w.minSize = new Vector2(740, 480);
    }

    // ---------- UI ----------

    private void OnGUI()
    {
        EnsureStyles();
        DrawHeader();
        EditorGUILayout.Space(4);

        if (!_scanned)
        {
            EditorGUILayout.HelpBox(
                "Scans every .prefab / .unity / .asset under Assets/ for MonoBehaviour blocks whose script GUID is missing. " +
                "For each missing GUID, gathers the property names that appear in YAML and ranks every MonoBehaviour and ScriptableObject in the project by how many of those property names it actually has as public or [SerializeField] fields.\n\n" +
                "Prerequisite: AssetRipper stub scripts must NOT be in the project (otherwise their GUIDs resolve and the entries don't show up as missing). Keep only your real source scripts and the SDK.",
                MessageType.Info);

            EditorGUILayout.Space(8);
            if (GUILayout.Button("Scan Project", GUILayout.Height(36)))
                Scan();
            return;
        }

        DrawSummary();
        DrawApplyBar();
        DrawList();
    }

    private void DrawHeader()
    {
        using (new EditorGUILayout.HorizontalScope(EditorStyles.toolbar))
        {
            GUILayout.Label("GUID Resolver", EditorStyles.boldLabel, GUILayout.Width(120));
            GUILayout.FlexibleSpace();
            if (_scanned)
            {
                if (GUILayout.Button("Re-scan", EditorStyles.toolbarButton, GUILayout.Width(70))) Scan();
                if (GUILayout.Button("Clear", EditorStyles.toolbarButton, GUILayout.Width(60)))
                {
                    _entries.Clear();
                    _scanned = false;
                    Repaint();
                }
            }
        }
    }

    private void DrawSummary()
    {
        if (_entries.Count == 0)
        {
            EditorGUILayout.HelpBox("No missing script references found in the project. ✓", MessageType.Info);
            return;
        }

        int conf = _entries.Count(e => e.Status == Status.Confident);
        int lik  = _entries.Count(e => e.Status == Status.Likely);
        int amb  = _entries.Count(e => e.Status == Status.Ambiguous);
        int par  = _entries.Count(e => e.Status == Status.Partial);
        int no   = _entries.Count(e => e.Status == Status.NoMatch);

        EditorGUILayout.LabelField(
            $"{_entries.Count} missing GUID(s):  " +
            $"✓ {conf} confident   ✓ {lik} likely   ? {amb} ambiguous   ~ {par} partial   ✗ {no} no-match",
            EditorStyles.boldLabel);

        using (new EditorGUILayout.HorizontalScope())
        {
            EditorGUILayout.LabelField("Filter:", GUILayout.Width(46));
            _filter = EditorGUILayout.TextField(_filter);
            if (GUILayout.Button("All", GUILayout.Width(50)))
                foreach (var e in _entries.Where(CanApply)) e.Apply = true;
            if (GUILayout.Button("None", GUILayout.Width(50)))
                foreach (var e in _entries) e.Apply = false;
            if (GUILayout.Button("Only Confident", GUILayout.Width(120)))
                foreach (var e in _entries) e.Apply = (e.Status == Status.Confident && CanApply(e));
        }
    }

    private void DrawApplyBar()
    {
        int willApply = _entries.Count(e => e.Apply && CanApply(e));
        using (new EditorGUI.DisabledScope(willApply == 0))
        {
            if (GUILayout.Button($"Apply {willApply} Remap(s)", GUILayout.Height(28)))
                ApplyAll();
        }
        EditorGUILayout.Space(4);
    }

    private void DrawList()
    {
        _scroll = EditorGUILayout.BeginScrollView(_scroll);
        try
        {
            foreach (var entry in _entries)
            {
                if (!string.IsNullOrEmpty(_filter))
                {
                    bool matches =
                        entry.MissingGuid.IndexOf(_filter, StringComparison.OrdinalIgnoreCase) >= 0
                        || entry.ObservedFields.Any(f => f.IndexOf(_filter, StringComparison.OrdinalIgnoreCase) >= 0)
                        || entry.Candidates.Any(c => c.Script.TypeName.IndexOf(_filter, StringComparison.OrdinalIgnoreCase) >= 0);
                    if (!matches) continue;
                }
                DrawEntry(entry);
            }
        }
        finally { EditorGUILayout.EndScrollView(); }
    }

    private void DrawEntry(MissingScriptEntry e)
    {
        using (new EditorGUILayout.VerticalScope("box"))
        {
            using (new EditorGUILayout.HorizontalScope())
            {
                using (new EditorGUI.DisabledScope(!CanApply(e)))
                    e.Apply = EditorGUILayout.Toggle(e.Apply, GUILayout.Width(18));

                GUILayout.Label(StatusIcon(e.Status), _statusStyles[(int)e.Status], GUILayout.Width(20));

                string title =
                    $"GUID {e.MissingGuid.Substring(0, 8)}...   " +
                    $"{e.UsedInFiles.Count} file(s)   " +
                    $"{e.ObservedFields.Count} field(s)";
                GUILayout.Label(title, EditorStyles.boldLabel);
                GUILayout.FlexibleSpace();
                GUILayout.Label(MatchLabel(e));

                if (GUILayout.Button(e.Expanded ? "▲" : "▼", GUILayout.Width(28)))
                    e.Expanded = !e.Expanded;
            }

            if (!e.Expanded) return;

            EditorGUILayout.Space(2);
            EditorGUI.indentLevel++;

            // Files using this missing script
            EditorGUILayout.LabelField($"Used in {e.UsedInFiles.Count} file(s):", EditorStyles.miniBoldLabel);
            int filesShown = Math.Min(e.UsedInFiles.Count, 8);
            for (int i = 0; i < filesShown; i++)
                EditorGUILayout.LabelField("  • " + e.UsedInFiles[i], EditorStyles.miniLabel);
            if (e.UsedInFiles.Count > filesShown)
                EditorGUILayout.LabelField($"  ... and {e.UsedInFiles.Count - filesShown} more", EditorStyles.miniLabel);

            EditorGUILayout.Space(2);

            // Detected fields
            EditorGUILayout.LabelField($"Detected serialized fields ({e.ObservedFields.Count}):", EditorStyles.miniBoldLabel);
            string fieldsText = string.Join(", ", e.ObservedFields.OrderBy(s => s));
            float h = Mathf.Clamp(14f * Mathf.Ceil(fieldsText.Length / 110f), 18f, 80f);
            EditorGUILayout.SelectableLabel(fieldsText, EditorStyles.wordWrappedMiniLabel, GUILayout.Height(h));

            EditorGUILayout.Space(2);

            // Candidates
            EditorGUILayout.LabelField("Candidates (sorted by coverage):", EditorStyles.miniBoldLabel);
            if (e.Candidates.Count == 0)
            {
                EditorGUILayout.HelpBox(
                    "No script in the project has any of these field names. The required script is probably missing — add the source .cs (or import the SDK that defines this type), then re-scan.",
                    MessageType.Warning);
            }
            else
            {
                int show = Math.Min(e.Candidates.Count, 6);
                for (int i = 0; i < show; i++)
                {
                    var c = e.Candidates[i];
                    bool isSelected = e.SelectedOverride == null
                        ? (i == 0 && (e.Status == Status.Confident || e.Status == Status.Likely))
                        : (e.SelectedOverride.Guid == c.Script.Guid);

                    using (new EditorGUILayout.HorizontalScope())
                    {
                        Color prev = GUI.color;
                        if (isSelected) GUI.color = new Color(0.55f, 1f, 0.55f);
                        if (GUILayout.Button(isSelected ? "●" : "○", GUILayout.Width(24)))
                            e.SelectedOverride = isSelected ? null : c.Script;
                        GUI.color = prev;

                        string label =
                            $"{c.Script.TypeName}    " +
                            $"{c.Matched}/{c.YamlFieldsTotal} matched ({c.Coverage:P0})    " +
                            $"script has {c.ScriptFieldsTotal} field(s)";
                        GUILayout.Label(label, GUILayout.ExpandWidth(true));

                        if (GUILayout.Button("Ping", GUILayout.Width(48)))
                        {
                            var mono = AssetDatabase.LoadAssetAtPath<MonoScript>(c.Script.AssetPath);
                            if (mono != null) EditorGUIUtility.PingObject(mono);
                        }
                    }

                    if (c.UnknownInScript != null && c.UnknownInScript.Count > 0)
                    {
                        string preview = c.UnknownInScript.Count > 8
                            ? string.Join(", ", c.UnknownInScript.Take(8)) + $", ... (+{c.UnknownInScript.Count - 8})"
                            : string.Join(", ", c.UnknownInScript);
                        EditorGUILayout.LabelField("    not in script: " + preview, EditorStyles.miniLabel);
                    }
                }
                if (e.Candidates.Count > show)
                    EditorGUILayout.LabelField($"  ... {e.Candidates.Count - show} weaker candidate(s) hidden", EditorStyles.miniLabel);
            }

            EditorGUILayout.Space(2);

            // Manual override
            using (new EditorGUILayout.HorizontalScope())
            {
                EditorGUILayout.LabelField("Manual pick:", GUILayout.Width(120));
                MonoScript current = e.SelectedOverride != null
                    ? AssetDatabase.LoadAssetAtPath<MonoScript>(e.SelectedOverride.AssetPath)
                    : null;
                MonoScript picked = (MonoScript)EditorGUILayout.ObjectField(current, typeof(MonoScript), false);
                if (picked != current)
                {
                    if (picked == null)
                    {
                        e.SelectedOverride = null;
                    }
                    else
                    {
                        string g = AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(picked));
                        if (_scriptByGuid.TryGetValue(g, out var info))
                        {
                            e.SelectedOverride = info;
                        }
                        else
                        {
                            EditorUtility.DisplayDialog(
                                "Not a MonoBehaviour / ScriptableObject",
                                "The script you picked does not derive from MonoBehaviour or ScriptableObject (or it failed to compile). Pick a different one.",
                                "OK");
                        }
                    }
                }
            }

            EditorGUI.indentLevel--;
            EditorGUILayout.Space(2);
        }
    }

    private static bool CanApply(MissingScriptEntry e)
    {
        if (e.SelectedOverride != null) return true;
        if (e.Candidates.Count == 0) return false;
        return e.Status == Status.Confident || e.Status == Status.Likely;
    }

    private static string StatusIcon(Status s) => s switch
    {
        Status.Confident => "✓",
        Status.Likely    => "✓",
        Status.Ambiguous => "?",
        Status.Partial   => "~",
        Status.NoMatch   => "✗",
        _ => "?"
    };

    private void EnsureStyles()
    {
        if (_statusStyles != null) return;
        _statusStyles = new GUIStyle[5];
        Color[] colors =
        {
            new Color(0.30f, 0.85f, 0.30f), // Confident
            new Color(0.60f, 0.90f, 0.30f), // Likely
            new Color(1.00f, 0.85f, 0.20f), // Ambiguous
            new Color(1.00f, 0.60f, 0.20f), // Partial
            new Color(1.00f, 0.30f, 0.30f), // NoMatch
        };
        for (int i = 0; i < 5; i++)
        {
            var s = new GUIStyle(EditorStyles.boldLabel);
            s.normal.textColor = colors[i];
            _statusStyles[i] = s;
        }
    }

    private static string MatchLabel(MissingScriptEntry e)
    {
        if (e.SelectedOverride != null)
            return $"→ {e.SelectedOverride.TypeName}  (manual)";
        if (e.Candidates.Count == 0) return "no candidates";

        switch (e.Status)
        {
            case Status.Confident: return $"→ {e.Candidates[0].Script.TypeName}  (confident)";
            case Status.Likely:    return $"→ {e.Candidates[0].Script.TypeName}  (likely)";
            case Status.Ambiguous:
            {
                int tied = e.Candidates.Count(c => c.Coverage >= HighConfidenceCoverage);
                return $"{tied} candidates tied — pick one";
            }
            case Status.Partial:
                return $"best: {e.Candidates[0].Script.TypeName} ({e.Candidates[0].Coverage:P0})";
            default: return "no good match";
        }
    }

    // ---------- Scan ----------

    private void Scan()
    {
        try
        {
            EditorUtility.DisplayProgressBar("GUID Resolver", "Indexing project scripts...", 0f);
            BuildScriptIndex();

            EditorUtility.DisplayProgressBar("GUID Resolver", "Enumerating asset files...", 0.05f);
            var files = Directory.EnumerateFiles(Application.dataPath, "*", SearchOption.AllDirectories)
                .Where(p => ScanExtensions.Contains(Path.GetExtension(p)))
                .ToList();

            EditorUtility.DisplayProgressBar("GUID Resolver", $"Scanning {files.Count} files...", 0.1f);

            // guid -> bag of (file, fieldsInThatBlock)
            var perGuid = new ConcurrentDictionary<string, ConcurrentBag<(string file, HashSet<string> fields)>>();

            Parallel.ForEach(files, file =>
            {
                try
                {
                    string text = File.ReadAllText(file);
                    if (text.IndexOf("MonoBehaviour:", StringComparison.Ordinal) < 0) return;
                    ProcessYamlFile(text, file, perGuid);
                }
                catch (Exception ex)
                {
                    Debug.LogWarning($"[GUID Resolver] Error reading {file}: {ex.Message}");
                }
            });

            EditorUtility.DisplayProgressBar("GUID Resolver", "Matching against project scripts...", 0.7f);

            _entries = new List<MissingScriptEntry>();
            foreach (var kv in perGuid)
            {
                var fieldUnion = new HashSet<string>(StringComparer.Ordinal);
                var filesList = new List<string>();
                var seenFiles = new HashSet<string>();
                foreach (var item in kv.Value)
                {
                    foreach (var f in item.fields) fieldUnion.Add(f);
                    if (seenFiles.Add(item.file)) filesList.Add(MakeProjectRelative(item.file));
                }
                filesList.Sort(StringComparer.OrdinalIgnoreCase);

                var entry = new MissingScriptEntry
                {
                    MissingGuid = kv.Key,
                    ObservedFields = fieldUnion,
                    UsedInFiles = filesList
                };
                ScoreCandidates(entry);
                _entries.Add(entry);
            }

            // Sort: ambiguous/partial/no-match first (they need attention), then likely, then confident.
            _entries.Sort((a, b) =>
            {
                int sa = StatusOrder(a.Status), sb = StatusOrder(b.Status);
                if (sa != sb) return sa.CompareTo(sb);
                return b.UsedInFiles.Count.CompareTo(a.UsedInFiles.Count);
            });

            _scanned = true;
        }
        finally
        {
            EditorUtility.ClearProgressBar();
            Repaint();
        }
    }

    private static int StatusOrder(Status s) => s switch
    {
        Status.Ambiguous => 0,
        Status.Partial   => 1,
        Status.NoMatch   => 2,
        Status.Likely    => 3,
        Status.Confident => 4,
        _ => 9
    };

    private void ProcessYamlFile(
        string text,
        string file,
        ConcurrentDictionary<string, ConcurrentBag<(string file, HashSet<string> fields)>> output)
    {
        const string DocSep = "--- !u!";
        int idx = 0;
        while ((idx = text.IndexOf(DocSep, idx, StringComparison.Ordinal)) >= 0)
        {
            int next = text.IndexOf("\n" + DocSep, idx + DocSep.Length, StringComparison.Ordinal);
            int end = next < 0 ? text.Length : next + 1;

            int headerEnd = text.IndexOf('\n', idx);
            if (headerEnd > 0 && headerEnd < end)
            {
                // Cheap: only !u!114 blocks contain MonoBehaviour/ScriptableObject data.
                int spaceAfterTag = text.IndexOf(' ', idx + DocSep.Length);
                if (spaceAfterTag > idx && spaceAfterTag < headerEnd)
                {
                    string tagNum = text.Substring(idx + DocSep.Length, spaceAfterTag - (idx + DocSep.Length));
                    if (tagNum == "114")
                    {
                        int bodyStart = headerEnd + 1;
                        // Body should start with "MonoBehaviour:" line.
                        if (bodyStart < end &&
                            string.CompareOrdinal(text, bodyStart, "MonoBehaviour:", 0, "MonoBehaviour:".Length) == 0)
                        {
                            string body = text.Substring(bodyStart, end - bodyStart);
                            ProcessMonoBehaviourBody(body, file, output);
                        }
                    }
                }
            }
            idx = end;
        }
    }

    private void ProcessMonoBehaviourBody(
        string body,
        string file,
        ConcurrentDictionary<string, ConcurrentBag<(string file, HashSet<string> fields)>> output)
    {
        var match = ScriptGuidRegex.Match(body);
        if (!match.Success) return;
        string guid = match.Groups[1].Value;

        // If a script with this GUID exists in the project, the reference is fine — skip.
        if (_scriptByGuid.ContainsKey(guid)) return;

        var fields = new HashSet<string>(StringComparer.Ordinal);
        var fmatches = TopLevelFieldRegex.Matches(body);
        foreach (Match fm in fmatches)
        {
            string name = fm.Groups[1].Value;
            if (SystemFields.Contains(name)) continue;
            fields.Add(name);
        }
        if (fields.Count == 0) return;

        var bag = output.GetOrAdd(guid, _ => new ConcurrentBag<(string, HashSet<string>)>());
        bag.Add((file, fields));
    }

    private void BuildScriptIndex()
    {
        _allScripts.Clear();
        _scriptByGuid.Clear();

        var monoScriptGuids = AssetDatabase.FindAssets("t:MonoScript");
        foreach (var guid in monoScriptGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            if (string.IsNullOrEmpty(path)) continue;
            var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
            if (script == null) continue;

            Type type = script.GetClass();
            if (type == null) continue;
            if (type.IsAbstract) continue;
            if (type.IsGenericTypeDefinition) continue;
            if (!typeof(MonoBehaviour).IsAssignableFrom(type) &&
                !typeof(ScriptableObject).IsAssignableFrom(type)) continue;

            var info = new ScriptInfo
            {
                Guid = guid,
                Type = type,
                AssetPath = path,
                TypeName = type.FullName ?? type.Name,
                Fields = GetSerializedFields(type)
            };
            _allScripts.Add(info);
            _scriptByGuid[guid] = info;
        }
    }

    private static HashSet<string> GetSerializedFields(Type type)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        Type t = type;
        while (t != null && t != typeof(MonoBehaviour) && t != typeof(ScriptableObject) && t != typeof(object))
        {
            var fields = t.GetFields(
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            foreach (var f in fields)
            {
                if (f.IsStatic) continue;
                if (f.IsLiteral) continue;          // const
                if (f.IsNotSerialized) continue;
                if (f.GetCustomAttribute<NonSerializedAttribute>() != null) continue;

                bool eligible = f.IsPublic || f.GetCustomAttribute<SerializeField>() != null;
                if (!eligible) continue;

                result.Add(f.Name);
            }
            t = t.BaseType;
        }
        return result;
    }

    private void ScoreCandidates(MissingScriptEntry entry)
    {
        if (entry.ObservedFields.Count == 0)
        {
            entry.Status = Status.NoMatch;
            return;
        }

        var matches = new List<CandidateMatch>();
        foreach (var s in _allScripts)
        {
            int hits = 0;
            List<string> unknown = null;
            foreach (var fld in entry.ObservedFields)
            {
                if (s.Fields.Contains(fld)) hits++;
                else
                {
                    unknown ??= new List<string>();
                    unknown.Add(fld);
                }
            }
            if (hits == 0) continue;

            matches.Add(new CandidateMatch
            {
                Script = s,
                Matched = hits,
                YamlFieldsTotal = entry.ObservedFields.Count,
                ScriptFieldsTotal = s.Fields.Count,
                Coverage = (float)hits / entry.ObservedFields.Count,
                UnknownInScript = unknown
            });
        }

        // Sort: highest coverage first; ties broken by tightness (fewer extra script fields), then name.
        matches.Sort((a, b) =>
        {
            int c = b.Coverage.CompareTo(a.Coverage);
            if (c != 0) return c;
            int aExtra = a.ScriptFieldsTotal - a.Matched;
            int bExtra = b.ScriptFieldsTotal - b.Matched;
            c = aExtra.CompareTo(bExtra);
            if (c != 0) return c;
            return string.Compare(a.Script.TypeName, b.Script.TypeName, StringComparison.Ordinal);
        });

        entry.Candidates = matches;

        int perfect = matches.Count(m => m.Coverage >= HighConfidenceCoverage);
        if (perfect == 1)
        {
            float secondBest = matches.Count > 1 ? matches[1].Coverage : 0f;
            entry.Status = secondBest < SecondBestThreshold ? Status.Confident : Status.Likely;
        }
        else if (perfect > 1)
        {
            entry.Status = Status.Ambiguous;
        }
        else if (matches.Count > 0 && matches[0].Coverage >= PartialThreshold)
        {
            entry.Status = Status.Partial;
        }
        else
        {
            entry.Status = Status.NoMatch;
        }
    }

    // ---------- Apply ----------

    private void ApplyAll()
    {
        var remap = new Dictionary<string, string>();
        var report = new StringBuilder();

        foreach (var e in _entries.Where(x => x.Apply && CanApply(x)))
        {
            ScriptInfo target = e.SelectedOverride
                ?? (e.Candidates.Count > 0 ? e.Candidates[0].Script : null);
            if (target == null) continue;
            if (string.Equals(e.MissingGuid, target.Guid, StringComparison.Ordinal)) continue;
            if (remap.ContainsKey(e.MissingGuid)) continue;
            remap[e.MissingGuid] = target.Guid;
            report.AppendLine($"  {e.MissingGuid}  →  {target.TypeName}  ({target.Guid})");
        }

        if (remap.Count == 0)
        {
            EditorUtility.DisplayDialog("Nothing to apply", "No remap entries selected.", "OK");
            return;
        }

        // Sanity: no target GUID should also be a key (would create a chained replace).
        foreach (var kv in remap)
        {
            if (remap.ContainsKey(kv.Value))
            {
                EditorUtility.DisplayDialog(
                    "Cyclic remap detected",
                    $"GUID {kv.Value} appears as both source and target. Aborting to avoid corruption.",
                    "OK");
                return;
            }
        }

        if (!EditorUtility.DisplayDialog(
            "Confirm GUID Remap",
            $"This will rewrite {remap.Count} GUID reference(s) across all eligible files in 'Assets/' and 'ProjectSettings/'.\n\n" +
            "Targets:\n" + report +
            "\nMake sure your project is committed or backed up. Continue?",
            "Apply", "Cancel"))
            return;

        AssetDatabase.SaveAssets();

        string projectRoot = Directory.GetParent(Application.dataPath).FullName;
        var roots = new[] { Application.dataPath, Path.Combine(projectRoot, "ProjectSettings") };

        var files = new List<string>();
        foreach (var root in roots)
        {
            if (!Directory.Exists(root)) continue;
            files.AddRange(Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories)
                .Where(p => PatchExtensions.Contains(Path.GetExtension(p))));
        }

        // Skip the .meta of any target script (their own GUID must remain intact — they ARE the asset).
        var targetMetas = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var kv in remap)
        {
            string targetPath = AssetDatabase.GUIDToAssetPath(kv.Value);
            if (string.IsNullOrEmpty(targetPath)) continue;
            string meta = Path.GetFullPath(Path.Combine(projectRoot, targetPath + ".meta"));
            targetMetas.Add(meta);
        }

        int modified = 0, errors = 0;

        EditorUtility.DisplayProgressBar("GUID Resolver", $"Patching {files.Count} files...", 0.1f);
        AssetDatabase.StartAssetEditing();
        try
        {
            Parallel.ForEach(files, file =>
            {
                try
                {
                    if (targetMetas.Contains(Path.GetFullPath(file))) return;

                    string text = File.ReadAllText(file);
                    bool changed = false;
                    foreach (var kv in remap)
                    {
                        if (text.IndexOf(kv.Key, StringComparison.Ordinal) >= 0)
                        {
                            text = text.Replace(kv.Key, kv.Value);
                            changed = true;
                        }
                    }
                    if (changed)
                    {
                        File.WriteAllText(file, text);
                        Interlocked.Increment(ref modified);
                    }
                }
                catch (Exception ex)
                {
                    Interlocked.Increment(ref errors);
                    Debug.LogWarning($"[GUID Resolver] Failed to patch {file}: {ex.Message}");
                }
            });
        }
        finally
        {
            AssetDatabase.StopAssetEditing();
            EditorUtility.ClearProgressBar();
        }

        AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);

        EditorUtility.DisplayDialog(
            "Done",
            $"Remapped {remap.Count} GUID(s).\n" +
            $"Files scanned: {files.Count}\n" +
            $"Files modified: {modified}" +
            (errors > 0 ? $"\nErrors: {errors} (see Console)" : ""),
            "OK");

        // Rescan to reflect the new state.
        Scan();
    }

    // ---------- Helpers ----------

    private static string MakeProjectRelative(string fullPath)
    {
        string proj = Directory.GetParent(Application.dataPath).FullName;
        if (fullPath.StartsWith(proj, StringComparison.OrdinalIgnoreCase))
            return fullPath.Substring(proj.Length + 1).Replace('\\', '/');
        return fullPath;
    }
}
